# Workflow Name
name: Hello

# When the workflow should run
on:
  workflow_dispatch:

# Jobs to execute
jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Say hello to everyone
        run: echo "Hello Dosto"
